# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestRegistration():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_registration(self):
        self.driver.get("http://localhost:3308/")
        self.driver.set_window_size(1502, 814)
        self.driver.find_element(By.LINK_TEXT, "LOG IN").click()
        self.driver.find_element(By.LINK_TEXT, "Register").click()
        self.driver.find_element(By.ID, "userId").click()
        self.driver.find_element(By.ID, "userId").click()
        self.driver.find_element(By.ID, "userId").send_keys("akhil")
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("akhil@gmail.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("Asd123")
        self.driver.find_element(By.ID, "check-box").click()
        self.driver.find_element(By.CSS_SELECTOR, ".submit-btn").click()
        self.driver.execute_script("window.scrollTo(0,0)")
